# Generated by Django 4.0.4 on 2022-05-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogdetailpage_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdetailpage',
            old_name='image',
            new_name='banner_image',
        ),
    ]
