# Generated by Django 4.0.4 on 2022-05-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('blog', '0006_rename_image_blogdetailpage_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlogPage',
            fields=[
                ('blogdetailpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blogdetailpage')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('intro_image', models.ForeignKey(blank=True, help_text='This is the Intro Image', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogdetailpage',),
        ),
    ]
