# Generated by Django 3.2.9 on 2021-12-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=70)),
                ('stu_pass', models.CharField(max_length=70)),
            ],
        ),
    ]
