# Generated by Django 3.2.9 on 2021-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=70)),
                ('stu_email', models.EmailField(max_length=70)),
                ('stu_pass', models.CharField(max_length=70)),
            ],
        ),
    ]
