# Generated by Django 4.0.4 on 2022-05-12 21:11

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0002_flexpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('Title_And_Text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add Title', max_length=100, required=True)), ('subtitle', wagtail.core.blocks.TextBlock(help_text='Add Subtitle', max_length=100, required=True))])), ('Rich_Text', streams.blocks.RichBlock()), ('LImited_Rich_Text', streams.blocks.LimitedRichBlock()), ('cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add a Title', required=True)), ('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_title', wagtail.core.blocks.CharBlock(help_text='Add Title To Your Image', max_length=50, required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add Subtitle To Your Image', max_length=100, required=False)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(help_text='If above page is selected, that will be used', required=False))])))])), ('cta', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('text', wagtail.core.blocks.RichTextBlock(features=['bold', 'italic'], required=True)), ('button_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('button_url', wagtail.core.blocks.URLBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(default='Learn More', max_length=70, required=False))]))], blank=True, null=True),
        ),
    ]
