# Generated by Django 3.2.9 on 2021-12-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='stu_com',
            field=models.CharField(default='Not Available', max_length=40),
        ),
    ]
